### ISSUE TITLE
Fare in modo che ci siano alcuni loghi dei produttori

### ISSUE THREAD

**Issue by feroda** [befair/sbcatalog#27]
Immagino inserire i loghi in Gasista Felice -> esportarli in GDXP -> importare il GDXP "as usual" su sbcatalog

Ma anche in qualche altro modo va bene, basta che ci siano alcuni loghi dei produttori su sbcatalog al più presto.

Precondizione per il rilascio della 0.1

**Comment by matteo88** [comment]
Rispondo: penso che il metodo migliore sia quello riportato nel commento precedente (inserire i loghi in Gasista Felice -> esportarli in GDXP -> importare il GDXP)

Sto raccogliendo i loghi da Dominique, non so quanti riuscirò ad averne, finora ne ho uno (ma chi ben cominicia.. )

**Comment by matteo88** [comment]
Proposta: nel frattempo qualcuno propone qualche altra fonte da cui potrei ricevere queste foto/loghi? Ad esempio, Loris puo essere adatto ? Se non altro per "La Terra e il Cielo"

Avete altri nominativi ?

**Comment by feroda** [comment]
Prendili dai siti, non chiederli alle persone. Assolutamente no Loris! e Assolutamente no produttori!

Se li trovi su altri siti gestionali GAS potrebbe essere carino per entrare in relazione con gli sviluppatori, ma dovrai avere tatto nel con-tatto perché il nostro scopo è aggregare e potenziare la forza comune, non impaurire facendo pensare che beFair si occuperà dei GAS d'ora in poi.

Puoi provare con Michele SBW dato che il contatto è frequente e non c'è bisogno di altre spiegazioni dato che è al corrente che stiamo per presentare questo progetto. Se vai su Social Marketplace (https://shop.socialbusinessworld.org) probabilmente ne troverai un po'

**Comment by matteo88** [comment]
Ok, quindi facendo capo ai produttori del DES (quelli ora presenti nell'export GDXP di GF ) considererò come fonti a cui chiedere loghi / immagini:
- Siti produttori --> domanda, se i loghi sono coperti da Copyright devo contattare il produttore prima di prendere la risorsa ? 
- Michele SBW
- altri gestionali (GASdotto ad esempio, ma anche altri) --> avrò tatto

**Comment by feroda** [comment]
vedi prima sul social marketplace. per il copyright direi di no se sono inseriti in GF.

**Comment by warp10** [comment]
Direi che possiamo chiusere la issue, visto che abbiamo i loghi e il necessario per mostrarli
