### ISSUE TITLE
Gestione filtro e paginazione

### ISSUE THREAD

**Issue by espositocloud** [befair/sbcatalog#31]
Attualmente la paginazione viene applicata prima del filtro, in particolare il filtro viene eseguito solo lato template, mentre la paginazione viene predisposta lato controller, e questo genera l'anomalia per cui con la select e' possibile filtrare solo gli elementi presenti nella pagina stessa.

**Comment by michelesr** [comment]
Per impementare la paginazione lato server è necessario capire come richiedere a eve il count del numero di pagine e i dati relativi a una pagina stessa.

**Comment by espositocloud** [comment]
Non dobbiamo necessariamente paginare lato server, ma e' fondamentale:
- filtrare prima
- paginare dopo

Quindi:
- se paginiamo lato server, dobbiamo per forza filtrare lato server
- se paginiamo lato client, possiamo scegliere se filtrare lato server o lato client

La prima cosa che punterei a fare e' vedere se si riesce a gestire tutto lato client, lavorando con controller e template.
