### ISSUE TITLE
Define GET GDXP endpoint and transfer POST GDXP endpoint

### ISSUE THREAD

**Issue by feroda** [befair/sbcatalog#4]
GET /gdxp/supplier -> return suppliers in GDXP format?
so mode POST /supplier/ with Content-type: text/xml to POST /gdxp/supplier/

**Comment by michelesr** [comment]
implementation started with commit 3c3d96144cc6d4340e3302a2d60ac919aea8667f

status: missing gdxp root attributes

**Comment by michelesr** [comment]
Siamo vicini al formato GDXP, l'unica cosa che sembra mancare è il campo `orders`, come specificato in #40 . Per me si può anche chiudere l'issue.

**Comment by feroda** [comment]
Il campo `orders` non _deve_ ;) essere implementato per ora. Nel formato è opzionale quindi va bene così. Provo a chiudere io la issue
