### ISSUE TITLE
[POLITICA] Ordini

### ISSUE THREAD

**Issue by michelesr** [befair/sbcatalog#40]
Conviene aggiungere il campo `orders` allo schema del db? Il ruolo di `sbcatalog` non dovrebbe essere quello di gestire gli ordini ne di importarli ed esportarli.

**Comment by feroda** [comment]
diciamo che la API esposta per l'economia solidale prevederà anche gli ordini, ma ad occhio questa API andrà bene anche senza ordini fino alla 1.0.

Per ora la gestione degli ordini è più un "desiderata", riceveremo molte osservazioni su quanto stiamo facendo, perciò per ora meglio non considerare nemmeno di introdurre la gestione del campo `orders`

Intendo che i feedback faranno anche evolvere il formato probabilmente. Non vale la pena mettercisi ora
