### ISSUE TITLE
Aggiungere un timestamp dei dati del supplier

### ISSUE THREAD

**Issue by warp10** [befair/sbcatalog#43]
Per ogni supplier all'interno del file GDXP, abbiamo bisogno di un field timestamp che ci dica qual è la data di ultimo aggiornamento dei dati del fornitore. Attenzione, non deve essere il timestamp del file, bensì delle informazioni relative al fornitore.

Questo bug richiede lavoro anche su GF (sfruttare anche Django reversion e django-pro-history)

**Comment by matteo88** [comment]
Sollevo una domanda: quando parlate dei "dati del fornitore", vi riferite ai soli dati dell'oggetto "Supplier", o anche ai dati degli oggetti "SupplierStock" inclusi all'interno del listino del fornitore, esportato in GDXP ?

**Comment by matteo88** [comment]
Visto l'utilizzo che dovremo andarne a fare (controllo della versione del listino per decidere se caricarlo o no in sbcatalog in luogo di quello più datato) propenderei per la seconda opzione

**Comment by matteo88** [comment]
A livello pratico, metterei una campo "last_updated_on" sia a livello del tag "supplier" che dei tag "product".

In alternativa, metterei un unico campo "last_updated_on"  a livello del tag "supplier" , che però contenga il più recente timestamp tra quello dell'oggetto Supplier e dei vari oggetti SupplierStock.
In fin dei conti, anche se uno solo di questi fosse stato aggiornato, dovremmo ricaricare tutto il GDXP, giusto ?

**Comment by matteo88** [comment]
Quanto detto sopra varrebbe nel caso di un GDXP con un solo fornitore, nel caso di GDXP multifornitore si vede il timestamp per ogni fornitore e si decide se sostituirlo o meno all'esistente (se esiste)

**Comment by warp10** [comment]
Ovviamente riguarda anche i dati di SupplierStock, che cambiano molto più frequentamente del Supplier (in linea di massima). Il campo last_update (senza "d_on" finale) è buono, puoi metterlo nel supplier e farlo riferire all'insieme del Supplier e dei SupplierStock ad esso collegati. +1 per l'ultimo commento invece.

**Comment by matteo88** [comment]
ok, se chiamassi la property in Supplier "last_catalog_update", per chiarezza ?

**Comment by warp10** [comment]
al massimo catalog_last_update, ma io eviterei, la specifica del GDXP chiarirà (eventualmente) di cosa si tratta.

**Comment by matteo88** [comment]
Aperta su befair/GasistaFelice PR  "Matteo dev gdxp timestamp" 61

**Comment by warp10** [comment]
PR mergiata in GF, possiamo considerare risolta questa issue
