### ISSUE TITLE
[UI] Pagina ABOUT con gli sviluppatori

### ISSUE THREAD

**Issue by feroda** [befair/sbcatalog#5]

**Comment by espositocloud** [comment]
I contenuti vanno inseriti nel file `frontend/components/about/index.jade`

**Comment by espositocloud** [comment]
In accordo con @warp10:
- le (macro)pagine `about` e `catalog` sono i componenti e devono essere scelti nella navbar
- le singole pagine di `sbcatalog` (relative alla paginazione) vanno invece messe come tab

**Comment by espositocloud** [comment]
Abilitato il routing per utilizzare la pagina nel #52 

La nuova pagina e' stata spostata in `frontend/components/about/about.jade` in accordo alle convenzioni del router.
