### ISSUE TITLE
La root url delle GET dev'essere parametrizzata in modo da semplificare il deploy

### ISSUE THREAD

**Issue by michelesr** [befair/sbcatalog#63]

**Comment by espositocloud** [comment]
Propongo di introdurre un file (opzionale) di configurazione in `frontend/settings.json`:
- `frontend/settings.json` da mettere nel `.gitignore`
- Angular effettua una get nell'`AppController` a `/settings.json` e setta il dizionario `settings` in `$rootScope`
- `settings` e' un dizionario che puo' contenere `apiBaseUrl` (di default a `localhost:5000`)
- modificare tutte le interazioni con il backend impostando come prefisso `$rootScope.settings.apiBaseUrl`
- in produzione andremo quindi a creare un file `frontend/settings.json` contente:

```
{
  "apiBaseUrl": "/api"
}
```

oppure

```
{
  "apiBaseUrl": "http://sbcatalog.labs.befair.it/api"
}
```
- infine documentare

**Comment by michelesr** [comment]
Già presente dalla PR #59
