### ISSUE TITLE
Gestione dei settings e containerizzazione

### ISSUE THREAD

**Issue by espositocloud** [befair/sbcatalog#64]
Al fine di:
- velocizzare il bootstrapping
- rendere immediatamente chiaro se sono stati settati dei parametri non di default
- predisporci per il (non troppo distante) futuro (CI, container..)

Propongo di:
- cancellare il `settings_dist.py`
- rinominare `default_settings.py` in `settings.py`
- dare la possibilita' di sovrascrivere i valori di default tramite un file (opzionale) chiamato `settings.yaml` o `settings.toml` (da decidere)
- nel `settings.py` verificare la presenza di un `settings.{yaml|toml}`, e in caso sovrascrivere i valori di default con quelli presenti nel file

**Comment by espositocloud** [comment]
Aggiornamenti:
- evitare il `.toml` in quanto linguaggio troppo giovane
- adottare un `settings.py` che include defaults e importa opzionalmente da:
  - file `sbcatalog/settings.yaml` (comodo da usare in sviluppo)
  - variabili d'ambiente (per la produzione nei container)

Altre cose non direttamente legate alla issue:
- introdurre [Docker Compose](https://docs.docker.com/compose/) per lo sviluppo (ed anche per la produzione temporaneamente)
- branch `stable` su Github, di riferimento per la produzione
- hook per il pull/deploy automatico in produzione ad ogni modifica sul branch `stable` se i test vanno a buon fine

**Comment by warp10** [comment]
Ho aggiunto un riferimento ai test al commento di @kobe25: il deploy automatico ha senso solo se implementiamo i test.

Direi che questa cosa possiamo cominciare a implementarla, e trarne esperienze esportabili in generali. Direi di mirare a 0.3, non è poi così urgente. Si può comunque anche portare avanti in più step: @kobe25, your call.

**Comment by espositocloud** [comment]
@warp10 ok per i test, invece pensavo di aprire un issue per docker-compose ma direi che va bene cosi'

**Comment by espositocloud** [comment]
Implementato in buona parte nel #74.

Rimane da aggiungere il supporto per il `settings.yaml`.
