### ISSUE TITLE
[UI] Visualizzare i prezzi dei prodotti nei listini

### ISSUE THREAD

**Issue by feroda** [befair/sbcatalog#8]

**Comment by feroda** [comment]
Chiudo questa issue perché @michelesr ha risolto il problema. 
Ha poi aggiunto un flag a livello di codice su mia richiesta per abilitare/disabilitare da codice la visualizzazione. Apro un'altra issue "politica" sui prezzi

**Comment by michelesr** [comment]
Attenzione, perchè in realtà il `flag` non esiste ancora.

**Comment by feroda** [comment]
era per stimolarti a metterlo ;)

A parte gli scherzi... non basta levare la checkbox che hai messo e mettere la variabile del modello a false? ;) Se cosi fosse... eddajeeeeeeee

**Comment by michelesr** [comment]
Pull request pronta a essere integrata.

Ho aggiunto un flag `SHOW_PRICES` in cima a `site.js`

**Comment by warp10** [comment]
Chiuso con la PR testè approvata
